"""empty message

Revision ID: 255c26027b98
Revises: a89d2b3afba8
Create Date: 2024-10-22 01:28:38.020303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255c26027b98'
down_revision = 'a89d2b3afba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('suscription_date', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lector')
    # ### end Alembic commands ###
