"""empty message

Revision ID: 29231e72439e
Revises: 2ab7a274856c
Create Date: 2024-11-22 07:16:57.727421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29231e72439e'
down_revision = '2ab7a274856c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critico', schema=None) as batch_op:
        batch_op.alter_column('acerca_de_mi',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=3000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critico', schema=None) as batch_op:
        batch_op.alter_column('acerca_de_mi',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
