"""empty message

Revision ID: b21a42f08a3b
Revises: cc0348aa5a9f
Create Date: 2024-11-06 21:05:54.359394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21a42f08a3b'
down_revision = 'cc0348aa5a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_lector_1', sa.Integer(), nullable=False),
    sa.Column('id_lector_2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_lector_1'], ['lector.id'], ),
    sa.ForeignKeyConstraint(['id_lector_2'], ['lector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_lector_1', sa.Integer(), nullable=False),
    sa.Column('id_lector_2', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['id_lector_1'], ['lector.id'], ),
    sa.ForeignKeyConstraint(['id_lector_2'], ['lector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('chat')
    # ### end Alembic commands ###
