"""empty message

Revision ID: cc0348aa5a9f
Revises: 9d90ee59b19b
Create Date: 2024-11-05 01:55:33.516413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0348aa5a9f'
down_revision = '9d90ee59b19b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critico', schema=None) as batch_op:
        batch_op.drop_constraint('critico_images_key', type_='unique')
        batch_op.drop_constraint('critico_nombre_key', type_='unique')

    with op.batch_alter_table('lector', schema=None) as batch_op:
        batch_op.drop_constraint('lector_images_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lector', schema=None) as batch_op:
        batch_op.create_unique_constraint('lector_images_key', ['images'])

    with op.batch_alter_table('critico', schema=None) as batch_op:
        batch_op.create_unique_constraint('critico_nombre_key', ['nombre'])
        batch_op.create_unique_constraint('critico_images_key', ['images'])

    # ### end Alembic commands ###
